/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace ERC1155Market {
  export type MarketItemStruct = {
    itemId: BigNumberish;
    nftContract: string;
    tokenId: BigNumberish;
    quantity: BigNumberish;
    seller: string;
    price: BigNumberish;
    status: BigNumberish;
  };

  export type MarketItemStructOutput = [
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    number
  ] & {
    itemId: BigNumber;
    nftContract: string;
    tokenId: BigNumber;
    quantity: BigNumber;
    seller: string;
    price: BigNumber;
    status: number;
  };
}

export interface ERC1155MarketInterface extends utils.Interface {
  contractName: "ERC1155Market";
  functions: {
    "buy(address,uint256,uint256)": FunctionFragment;
    "cancelMarketItem(uint256,uint256)": FunctionFragment;
    "createMarketItem(address,uint256,uint256,uint256)": FunctionFragment;
    "fetchItemsCreated(address)": FunctionFragment;
    "fetchMarketItems()": FunctionFragment;
    "fetchMyNFTs(address)": FunctionFragment;
    "getListingPrice()": FunctionFragment;
    "owner()": FunctionFragment;
    "owners(uint256,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "buy",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMarketItem",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarketItem",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fetchItemsCreated",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "fetchMarketItems",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fetchMyNFTs", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getListingPrice",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "owners",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelMarketItem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarketItem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchItemsCreated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchMarketItems",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchMyNFTs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getListingPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owners", data: BytesLike): Result;

  events: {
    "ListingBuy(uint256,address,uint256,uint256,address,address)": EventFragment;
    "ListingCancelled(uint256,uint256)": EventFragment;
    "ListingCreated(uint256,address,uint256,uint256,address,uint256)": EventFragment;
    "RoyaltyPaid(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ListingBuy"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ListingCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ListingCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoyaltyPaid"): EventFragment;
}

export type ListingBuyEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber, string, string],
  {
    itemId: BigNumber;
    nftContract: string;
    tokenId: BigNumber;
    quantity: BigNumber;
    seller: string;
    buyer: string;
  }
>;

export type ListingBuyEventFilter = TypedEventFilter<ListingBuyEvent>;

export type ListingCancelledEvent = TypedEvent<
  [BigNumber, BigNumber],
  { itemId: BigNumber; quantity: BigNumber }
>;

export type ListingCancelledEventFilter =
  TypedEventFilter<ListingCancelledEvent>;

export type ListingCreatedEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber, string, BigNumber],
  {
    itemId: BigNumber;
    nftContract: string;
    tokenId: BigNumber;
    quantity: BigNumber;
    seller: string;
    price: BigNumber;
  }
>;

export type ListingCreatedEventFilter = TypedEventFilter<ListingCreatedEvent>;

export type RoyaltyPaidEvent = TypedEvent<
  [string, BigNumber],
  { receiver: string; amount: BigNumber }
>;

export type RoyaltyPaidEventFilter = TypedEventFilter<RoyaltyPaidEvent>;

export interface ERC1155Market extends BaseContract {
  contractName: "ERC1155Market";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ERC1155MarketInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    buy(
      nftContract: string,
      itemId: BigNumberish,
      quantity_: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelMarketItem(
      itemId: BigNumberish,
      quantity_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createMarketItem(
      nftContract: string,
      tokenId: BigNumberish,
      quantity_: BigNumberish,
      price: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    fetchItemsCreated(
      sender: string,
      overrides?: CallOverrides
    ): Promise<[ERC1155Market.MarketItemStructOutput[]]>;

    fetchMarketItems(
      overrides?: CallOverrides
    ): Promise<[ERC1155Market.MarketItemStructOutput[]]>;

    fetchMyNFTs(
      sender: string,
      overrides?: CallOverrides
    ): Promise<[ERC1155Market.MarketItemStructOutput[], BigNumber[]]>;

    getListingPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    owners(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  buy(
    nftContract: string,
    itemId: BigNumberish,
    quantity_: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelMarketItem(
    itemId: BigNumberish,
    quantity_: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createMarketItem(
    nftContract: string,
    tokenId: BigNumberish,
    quantity_: BigNumberish,
    price: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  fetchItemsCreated(
    sender: string,
    overrides?: CallOverrides
  ): Promise<ERC1155Market.MarketItemStructOutput[]>;

  fetchMarketItems(
    overrides?: CallOverrides
  ): Promise<ERC1155Market.MarketItemStructOutput[]>;

  fetchMyNFTs(
    sender: string,
    overrides?: CallOverrides
  ): Promise<[ERC1155Market.MarketItemStructOutput[], BigNumber[]]>;

  getListingPrice(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  owners(
    arg0: BigNumberish,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    buy(
      nftContract: string,
      itemId: BigNumberish,
      quantity_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelMarketItem(
      itemId: BigNumberish,
      quantity_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createMarketItem(
      nftContract: string,
      tokenId: BigNumberish,
      quantity_: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    fetchItemsCreated(
      sender: string,
      overrides?: CallOverrides
    ): Promise<ERC1155Market.MarketItemStructOutput[]>;

    fetchMarketItems(
      overrides?: CallOverrides
    ): Promise<ERC1155Market.MarketItemStructOutput[]>;

    fetchMyNFTs(
      sender: string,
      overrides?: CallOverrides
    ): Promise<[ERC1155Market.MarketItemStructOutput[], BigNumber[]]>;

    getListingPrice(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    owners(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "ListingBuy(uint256,address,uint256,uint256,address,address)"(
      itemId?: BigNumberish | null,
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      quantity?: null,
      seller?: null,
      buyer?: null
    ): ListingBuyEventFilter;
    ListingBuy(
      itemId?: BigNumberish | null,
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      quantity?: null,
      seller?: null,
      buyer?: null
    ): ListingBuyEventFilter;

    "ListingCancelled(uint256,uint256)"(
      itemId?: BigNumberish | null,
      quantity?: null
    ): ListingCancelledEventFilter;
    ListingCancelled(
      itemId?: BigNumberish | null,
      quantity?: null
    ): ListingCancelledEventFilter;

    "ListingCreated(uint256,address,uint256,uint256,address,uint256)"(
      itemId?: BigNumberish | null,
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      quantity?: null,
      seller?: null,
      price?: null
    ): ListingCreatedEventFilter;
    ListingCreated(
      itemId?: BigNumberish | null,
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      quantity?: null,
      seller?: null,
      price?: null
    ): ListingCreatedEventFilter;

    "RoyaltyPaid(address,uint256)"(
      receiver?: string | null,
      amount?: BigNumberish | null
    ): RoyaltyPaidEventFilter;
    RoyaltyPaid(
      receiver?: string | null,
      amount?: BigNumberish | null
    ): RoyaltyPaidEventFilter;
  };

  estimateGas: {
    buy(
      nftContract: string,
      itemId: BigNumberish,
      quantity_: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelMarketItem(
      itemId: BigNumberish,
      quantity_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createMarketItem(
      nftContract: string,
      tokenId: BigNumberish,
      quantity_: BigNumberish,
      price: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    fetchItemsCreated(
      sender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fetchMarketItems(overrides?: CallOverrides): Promise<BigNumber>;

    fetchMyNFTs(sender: string, overrides?: CallOverrides): Promise<BigNumber>;

    getListingPrice(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    owners(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buy(
      nftContract: string,
      itemId: BigNumberish,
      quantity_: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelMarketItem(
      itemId: BigNumberish,
      quantity_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createMarketItem(
      nftContract: string,
      tokenId: BigNumberish,
      quantity_: BigNumberish,
      price: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    fetchItemsCreated(
      sender: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fetchMarketItems(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fetchMyNFTs(
      sender: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getListingPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owners(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
